# FluLink 星尘共鸣版 v4.0 - Zeabur 部署配置

services:
  # PocketBase 后端服务
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
      - PB_HOOKS_DIR=/app/pocketbase/hooks
      - PB_PUBLIC_URL=${PUBLIC_URL}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
    volumes:
      - pb_data:/pb_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI 智能服务
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_URL=${CHROMA_DB_URL}
      - POCKETBASE_URL=${POCKETBASE_URL}
    depends_on:
      - pocketbase
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:8080
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=${POCKETBASE_URL}
      - NEXT_PUBLIC_AI_SERVICE_URL=${AI_SERVICE_URL}
      - NODE_ENV=production
    depends_on:
      - pocketbase
      - ai-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pb_data:
    driver: local

networks:
  default:
    driver: bridge